name: kimhalliday
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.09785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d2d1e'
    - '#816649'
    - '#685036'
    - '#0a0603'
    - '#251b11'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
