name: 'kim halliday - composer & musician'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4605735
title: 'kim halliday - composer & musician'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7aa91'
    - '#000000'
    - '#a26854'
    - '#241c1a'
    - '#ffd6c3'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
