name: kimhalliday
favicon: null
layout_spectrum: 0.12402
typography_spectrum: 0.15461
title: 'kim halliday - composer & musician'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#727272'
    - '#464646'
    - '#d7d7d7'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
