name: kimhalliday
favicon: null
layout_spectrum: 0.50489
typography_spectrum: 0.34247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#282a16'
    - '#9e98a2'
    - '#686461'
    - '#fefefe'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
