name: kimhalliday
favicon: null
layout_spectrum: 0.88954
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d2d1e'
    - '#816649'
    - '#685036'
    - '#0a0603'
    - '#251b11'
  brandStrength: 0.375
  lightness: 0.7126177810132504
  saturation: 0.25
  rhythmicContrast: 0.6283959303982556
purpose: []
