name: kimhalliday
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47359
title: 'kim halliday - composer & musician'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#727272'
    - '#464646'
    - '#d7d7d7'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
